#!/bin/sh
#
# Starts dovecot.
#

start() {
	echo -n "Starting dovecot: "
	start-stop-daemon -S -q -p /var/run/dovecot.pid --exec /usr/sbin/dovecot -- -c /etc/dovecot/dovecot.conf
	echo "OK"
}
stop() {
	echo -n "Stopping dovecot: "
	start-stop-daemon -K -q -p /var/run/dovecot.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

