#!/bin/sh
#
# Starts fetchmail.
#

start() {
	echo -n "Starting fetchmail: "
	start-stop-daemon -S -q -p /var/run/fetchmail.pid --exec /usr/sbin/fetchmail -- -d 300 --pidfile /var/run/fetchmail.pid -f /etc/fetchmail.conf
	echo "OK"
}
stop() {
	echo -n "Stopping fetchmail: "
	start-stop-daemon -K -q -p /var/run/fetchmail.pid
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

