#!/bin/sh
echo "Waiting for MySQL"
while ! pidof mysqld >> /dev/null ;
do
sleep 1
done

echo "Setting up system."
mysqladmin -u root password @MYSQL_DB_PASSWORD@
echo "CREATE USER 'owncloud'@'localhost' IDENTIFIED BY '@OWNCLOUD_DB_PASSWORD@';" > /tmp/mysql_owncloud_init.sql
echo "CREATE DATABASE IF NOT EXISTS owncloud;" >> /tmp/mysql_owncloud_init.sql
echo "GRANT ALL PRIVILEGES ON owncloud.* TO 'owncloud'@'localhost' IDENTIFIED BY '@OWNCLOUD_DB_PASSWORD@';" >> /tmp/mysql_owncloud_init.sql
mysql -u root --password=@MYSQL_DB_PASSWORD@ < /tmp/mysql_owncloud_init.sql
# Delete me
rm /etc/init.d/S98autosetup
